# Generated by Django 3.2.3 on 2021-11-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0003_auto_20211119_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='service_name',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Service name'),
        ),
    ]
